name: vib3_flutter
description: "VIB3 - Short-form video sharing social media app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  video_player: ^2.8.2
  chewie: ^1.7.4
  http: ^1.1.2
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  permission_handler: ^11.1.0
  cached_network_image: ^3.3.1
  provider: ^6.1.1
  shimmer: ^3.0.0
  flutter_cache_manager: ^3.3.1
  visibility_detector: ^0.4.0+2
  flutter_spinkit: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/