name: vib3-backend
region: nyc
services:
  - name: api
    github:
      repo: Vibe-Hacker/vib3
      branch: main
      deploy_on_push: true
    source_dir: /
    build_command: npm install
    run_command: node server.js
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 3000
    envs:
    - key: NODE_ENV
      value: production
    - key: PORT
      value: "3000"
    # NOTE: Sensitive environment variables (DATABASE_URL, JWT_SECRET, API keys, etc.)
    # should be configured directly in the Digital Ocean App Platform dashboard
    # under Settings > App-Level Environment Variables for security