name: vib3-backend
region: nyc
services:
  - name: api
    github:
      repo: Vibe-Hacker/vib3
      branch: main
      deploy_on_push: true
    source_dir: /
    build_command: npm install
    run_command: node server.js
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 3000
    envs:
    - key: NODE_ENV
      value: production
      scope: RUN_TIME
    - key: PORT
      value: "3000"
      scope: RUN_TIME
    - key: DO_SPACES_KEY
      value: DO00RUBQWDCCVRFEWBFF
      scope: RUN_TIME
    - key: DO_SPACES_SECRET
      value: 05J/3Y+QIh5a83Eag5rFxnp4RNhNOqfwVNUjbKNuqn8
      scope: RUN_TIME
    - key: DO_SPACES_BUCKET
      value: vib3-videos
      scope: RUN_TIME
    - key: DO_SPACES_REGION
      value: nyc3
      scope: RUN_TIME