name: vib3-backend
region: nyc
services:
  - name: api
    github:
      repo: Vibe-Hacker/vib3
      branch: main
      deploy_on_push: true
    source_dir: /
    build_command: npm install
    run_command: node server.js
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 3000
    envs:
    - key: NODE_ENV
      value: production
      scope: RUN_TIME
    - key: PORT
      value: "3000"
      scope: RUN_TIME
    # IMPORTANT: Add these environment variables in Digital Ocean App Platform dashboard:
    # - DATABASE_URL: Your MongoDB connection string (from .env file)
    # - JWT_SECRET: Your JWT secret key (from .env file)
    # - DO_SPACES_KEY, DO_SPACES_SECRET, DO_SPACES_BUCKET, DO_SPACES_REGION
    # - GROK_API_KEY (optional)
    #
    # To add them:
    # 1. Go to https://cloud.digitalocean.com/apps
    # 2. Select your app (vib3-backend)
    # 3. Go to Settings tab
    # 4. Click "Edit" next to "Environment Variables"
    # 5. Add each variable listed above