global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'vib3-production'
    env: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Load rules
rule_files:
  - "alerts/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter - System metrics
  - job_name: 'node'
    static_configs:
      - targets:
          - 'node-exporter:9100'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+).*'

  # API Gateway metrics
  - job_name: 'api-gateway'
    static_configs:
      - targets:
          - 'api-gateway:4000'
    metrics_path: '/metrics'

  # Microservices metrics
  - job_name: 'microservices'
    static_configs:
      - targets:
          - 'auth-service:3001'
          - 'video-service:3002'
          - 'user-service:3003'
          - 'recommendation-service:3004'
          - 'analytics-service:3005'
          - 'notification-service:3006'
    metrics_path: '/metrics'
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        regex: '([^:]+).*'

  # MongoDB Exporter
  - job_name: 'mongodb'
    static_configs:
      - targets:
          - 'mongodb-exporter:9216'

  # Redis Exporter
  - job_name: 'redis'
    static_configs:
      - targets:
          - 'redis-exporter:9121'

  # RabbitMQ Exporter
  - job_name: 'rabbitmq'
    static_configs:
      - targets:
          - 'rabbitmq:15692'
    metrics_path: '/metrics'

  # Elasticsearch Exporter
  - job_name: 'elasticsearch'
    static_configs:
      - targets:
          - 'elasticsearch-exporter:9114'

  # Nginx Exporter
  - job_name: 'nginx'
    static_configs:
      - targets:
          - 'nginx-exporter:9113'

  # Docker containers
  - job_name: 'cadvisor'
    static_configs:
      - targets:
          - 'cadvisor:8080'
    metric_relabel_configs:
      # Only keep important container metrics
      - source_labels: [__name__]
        regex: 'container_(cpu_usage_seconds_total|memory_usage_bytes|network_receive_bytes_total|network_transmit_bytes_total|fs_usage_bytes)'
        action: keep

  # Kubernetes cluster (if using K8s)
  - job_name: 'kubernetes-apiservers'
    kubernetes_sd_configs:
      - role: endpoints
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    relabel_configs:
      - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
        action: keep
        regex: default;kubernetes;https

  # Custom application metrics
  - job_name: 'application'
    static_configs:
      - targets:
          - 'api-gateway:4000'
    metrics_path: '/api/metrics'
    params:
      format: ['prometheus']

# Remote write for long-term storage
remote_write:
  - url: 'http://thanos-receive:19291/api/v1/receive'
    write_relabel_configs:
      - source_labels: [__name__]
        regex: 'go_.*'
        action: drop

# Remote read for querying historical data
remote_read:
  - url: 'http://thanos-query:9090/api/v1/read'
    read_recent: true