name: Basic Flutter Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
        
    - name: Setup Java 11
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '11'
        
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.10.6'
        channel: 'stable'
        
    - name: Check Flutter
      run: flutter --version
        
    - name: Get dependencies
      run: |
        cd vib3_flutter
        flutter pub get
        
    - name: Build APK
      run: |
        cd vib3_flutter
        flutter build apk
        
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: flutter-apk
        path: vib3_flutter/build/app/outputs/flutter-apk/*.apk