name: Basic Flutter Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
        
    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '17'
        
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.2'
        channel: 'stable'
        
    - name: Check Flutter
      run: flutter --version
        
    - name: Get dependencies
      run: |
        cd vib3_app
        flutter pub get
        
    - name: Build APK
      run: |
        cd vib3_app
        flutter build apk
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: flutter-apk
        path: vib3_app/build/app/outputs/flutter-apk/*.apk