name: Build VIB3 APK

on:
  workflow_dispatch:  # Only run manually, not on every push

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Debug - List repository structure
      run: |
        echo "Repository root:"
        ls -la
        echo ""
        echo "Checking for vib3_app:"
        if [ -d "vib3_app" ]; then
          echo "vib3_app directory exists"
          ls -la vib3_app/
        else
          echo "ERROR: vib3_app directory NOT FOUND"
        fi
      
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.2'
        
    - name: Install dependencies
      run: |
        cd vib3_app
        flutter pub get
        
    - name: Build APK
      run: |
        cd vib3_app
        flutter build apk --release
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: vib3-apk
        path: vib3_app/build/app/outputs/flutter-apk/app-release.apk